// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlterTable(arg1, arg2, arg3) {
  return window['go']['app']['App']['AlterTable'](arg1, arg2, arg3);
}

export function ApplyChanges(arg1) {
  return window['go']['app']['App']['ApplyChanges'](arg1);
}

export function BuildFilterSQL(arg1, arg2) {
  return window['go']['app']['App']['BuildFilterSQL'](arg1, arg2);
}

export function CancelExecution(arg1) {
  return window['go']['app']['App']['CancelExecution'](arg1);
}

export function CancelOperation(arg1) {
  return window['go']['app']['App']['CancelOperation'](arg1);
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function CloseConnection(arg1) {
  return window['go']['app']['App']['CloseConnection'](arg1);
}

export function CloseResult(arg1) {
  return window['go']['app']['App']['CloseResult'](arg1);
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function CountResultRows(arg1) {
  return window['go']['app']['App']['CountResultRows'](arg1);
}

export function CountTableRows(arg1, arg2, arg3) {
  return window['go']['app']['App']['CountTableRows'](arg1, arg2, arg3);
}

export function CreateDatabase(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateDatabase'](arg1, arg2, arg3, arg4);
}

export function CreateDatabaseFileDialog() {
  return window['go']['app']['App']['CreateDatabaseFileDialog']();
}

export function CreateSchema(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateSchema'](arg1, arg2, arg3);
}

export function CreateTable(arg1, arg2) {
  return window['go']['app']['App']['CreateTable'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteDraft(arg1) {
  return window['go']['app']['App']['DeleteDraft'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['app']['App']['DeleteGroup'](arg1);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['app']['App']['DeleteSavedQuery'](arg1);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['app']['App']['DropDatabase'](arg1, arg2);
}

export function DropObject(arg1, arg2) {
  return window['go']['app']['App']['DropObject'](arg1, arg2);
}

export function DropSchema(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DropSchema'](arg1, arg2, arg3, arg4);
}

export function DuplicateConnection(arg1) {
  return window['go']['app']['App']['DuplicateConnection'](arg1);
}

export function ExecuteSQL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExecuteSQL'](arg1, arg2, arg3, arg4);
}

export function ExplainSQL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExplainSQL'](arg1, arg2, arg3, arg4);
}

export function ExportResultSet(arg1, arg2) {
  return window['go']['app']['App']['ExportResultSet'](arg1, arg2);
}

export function FetchRows(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchRows'](arg1, arg2, arg3);
}

export function FormatSQL(arg1, arg2) {
  return window['go']['app']['App']['FormatSQL'](arg1, arg2);
}

export function GenerateInsertSQL(arg1, arg2) {
  return window['go']['app']['App']['GenerateInsertSQL'](arg1, arg2);
}

export function GenerateRowSQL(arg1, arg2) {
  return window['go']['app']['App']['GenerateRowSQL'](arg1, arg2);
}

export function GenerateSelectSQL(arg1, arg2, arg3) {
  return window['go']['app']['App']['GenerateSelectSQL'](arg1, arg2, arg3);
}

export function GenerateUpdateSQL(arg1, arg2) {
  return window['go']['app']['App']['GenerateUpdateSQL'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetCellValue(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCellValue'](arg1, arg2, arg3);
}

export function GetHistory(arg1) {
  return window['go']['app']['App']['GetHistory'](arg1);
}

export function GetObjectDDL(arg1, arg2) {
  return window['go']['app']['App']['GetObjectDDL'](arg1, arg2);
}

export function GetResourceStats() {
  return window['go']['app']['App']['GetResourceStats']();
}

export function GetResultStats(arg1) {
  return window['go']['app']['App']['GetResultStats'](arg1);
}

export function GetSavedQueries() {
  return window['go']['app']['App']['GetSavedQueries']();
}

export function GetServerInfo(arg1) {
  return window['go']['app']['App']['GetServerInfo'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetStatementAt(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetStatementAt'](arg1, arg2, arg3);
}

export function GetTableDefinition(arg1, arg2) {
  return window['go']['app']['App']['GetTableDefinition'](arg1, arg2);
}

export function GetTableStats(arg1, arg2) {
  return window['go']['app']['App']['GetTableStats'](arg1, arg2);
}

export function ImportPlugin(arg1) {
  return window['go']['app']['App']['ImportPlugin'](arg1);
}

export function ImportPluginDialog() {
  return window['go']['app']['App']['ImportPluginDialog']();
}

export function InitialAppearance() {
  return window['go']['app']['App']['InitialAppearance']();
}

export function LanguagePreference() {
  return window['go']['app']['App']['LanguagePreference']();
}

export function ListAllDatabases(arg1) {
  return window['go']['app']['App']['ListAllDatabases'](arg1);
}

export function ListConnections() {
  return window['go']['app']['App']['ListConnections']();
}

export function ListDatabases(arg1) {
  return window['go']['app']['App']['ListDatabases'](arg1);
}

export function ListDrafts() {
  return window['go']['app']['App']['ListDrafts']();
}

export function ListEngines() {
  return window['go']['app']['App']['ListEngines']();
}

export function ListFavorites() {
  return window['go']['app']['App']['ListFavorites']();
}

export function ListFilterOps() {
  return window['go']['app']['App']['ListFilterOps']();
}

export function ListGroups() {
  return window['go']['app']['App']['ListGroups']();
}

export function ListObjects(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListObjects'](arg1, arg2, arg3, arg4);
}

export function ListPlugins() {
  return window['go']['app']['App']['ListPlugins']();
}

export function ListSchemas(arg1, arg2) {
  return window['go']['app']['App']['ListSchemas'](arg1, arg2);
}

export function McpCallTool(arg1, arg2, arg3) {
  return window['go']['app']['App']['McpCallTool'](arg1, arg2, arg3);
}

export function McpReadResource(arg1, arg2) {
  return window['go']['app']['App']['McpReadResource'](arg1, arg2);
}

export function McpResources(arg1) {
  return window['go']['app']['App']['McpResources'](arg1);
}

export function McpTools(arg1) {
  return window['go']['app']['App']['McpTools'](arg1);
}

export function MoveConnection(arg1, arg2) {
  return window['go']['app']['App']['MoveConnection'](arg1, arg2);
}

export function OpenConnection(arg1) {
  return window['go']['app']['App']['OpenConnection'](arg1);
}

export function OpenDatabaseFileDialog() {
  return window['go']['app']['App']['OpenDatabaseFileDialog']();
}

export function OpenSQLFileDialog() {
  return window['go']['app']['App']['OpenSQLFileDialog']();
}

export function OpenTableData(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenTableData'](arg1, arg2, arg3);
}

export function PingConnection(arg1) {
  return window['go']['app']['App']['PingConnection'](arg1);
}

export function PluginNodeActions(arg1, arg2) {
  return window['go']['app']['App']['PluginNodeActions'](arg1, arg2);
}

export function PreviewAlterTable(arg1, arg2, arg3) {
  return window['go']['app']['App']['PreviewAlterTable'](arg1, arg2, arg3);
}

export function PreviewChanges(arg1) {
  return window['go']['app']['App']['PreviewChanges'](arg1);
}

export function PreviewCreateTable(arg1, arg2) {
  return window['go']['app']['App']['PreviewCreateTable'](arg1, arg2);
}

export function ReadLogTail(arg1) {
  return window['go']['app']['App']['ReadLogTail'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['app']['App']['ReadTextFile'](arg1);
}

export function RedisCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisCommand'](arg1, arg2, arg3);
}

export function RedisDeleteKeys(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisDeleteKeys'](arg1, arg2, arg3);
}

export function RedisExpireKey(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisExpireKey'](arg1, arg2, arg3, arg4);
}

export function RedisGetKey(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisGetKey'](arg1, arg2, arg3);
}

export function RedisRenameKey(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisRenameKey'](arg1, arg2, arg3, arg4);
}

export function RedisScanKeys(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisScanKeys'](arg1, arg2, arg3, arg4);
}

export function RedisSetKey(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisSetKey'](arg1, arg2, arg3);
}

export function RefreshRow(arg1, arg2) {
  return window['go']['app']['App']['RefreshRow'](arg1, arg2);
}

export function ReleaseMemory() {
  return window['go']['app']['App']['ReleaseMemory']();
}

export function RemovePlugin(arg1) {
  return window['go']['app']['App']['RemovePlugin'](arg1);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['app']['App']['RenameGroup'](arg1, arg2);
}

export function RenameObject(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenameObject'](arg1, arg2, arg3);
}

export function ReorderConnections(arg1) {
  return window['go']['app']['App']['ReorderConnections'](arg1);
}

export function ReorderGroups(arg1) {
  return window['go']['app']['App']['ReorderGroups'](arg1);
}

export function ResolvedLanguage() {
  return window['go']['app']['App']['ResolvedLanguage']();
}

export function RevealLogFile() {
  return window['go']['app']['App']['RevealLogFile']();
}

export function RevealPlugin(arg1) {
  return window['go']['app']['App']['RevealPlugin'](arg1);
}

export function RunPluginAction(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RunPluginAction'](arg1, arg2, arg3, arg4);
}

export function SaveConnection(arg1) {
  return window['go']['app']['App']['SaveConnection'](arg1);
}

export function SaveDraft(arg1) {
  return window['go']['app']['App']['SaveDraft'](arg1);
}

export function SaveFileDialogFor(arg1, arg2) {
  return window['go']['app']['App']['SaveFileDialogFor'](arg1, arg2);
}

export function SaveGroup(arg1) {
  return window['go']['app']['App']['SaveGroup'](arg1);
}

export function SaveQuery(arg1) {
  return window['go']['app']['App']['SaveQuery'](arg1);
}

export function SaveSQLFileDialog(arg1) {
  return window['go']['app']['App']['SaveSQLFileDialog'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function Search(arg1) {
  return window['go']['app']['App']['Search'](arg1);
}

export function ServerVariables(arg1) {
  return window['go']['app']['App']['ServerVariables'](arg1);
}

export function SetCurrentDatabase(arg1, arg2) {
  return window['go']['app']['App']['SetCurrentDatabase'](arg1, arg2);
}

export function SplitStatements(arg1, arg2) {
  return window['go']['app']['App']['SplitStatements'](arg1, arg2);
}

export function StopFetch(arg1) {
  return window['go']['app']['App']['StopFetch'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}

export function ThemePreference() {
  return window['go']['app']['App']['ThemePreference']();
}

export function TitleBarDoubleClickAction() {
  return window['go']['app']['App']['TitleBarDoubleClickAction']();
}

export function ToggleFavorite(arg1) {
  return window['go']['app']['App']['ToggleFavorite'](arg1);
}

export function TruncateTable(arg1, arg2) {
  return window['go']['app']['App']['TruncateTable'](arg1, arg2);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['app']['App']['WriteTextFile'](arg1, arg2);
}
