// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dbx} from '../models';
import {app} from '../models';
import {context} from '../models';
import {rs} from '../models';
import {store} from '../models';
import {sqlutil} from '../models';
import {mcp} from '../models';
import {plugindrv} from '../models';

export function AlterTable(arg1:string,arg2:dbx.TableDefinition,arg3:dbx.TableDefinition):Promise<void>;

export function ApplyChanges(arg1:app.ChangeSet):Promise<app.ApplyResult>;

export function BuildFilterSQL(arg1:string,arg2:app.FilterGroup):Promise<string>;

export function CancelExecution(arg1:string):Promise<void>;

export function CancelOperation(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function CloseConnection(arg1:string):Promise<void>;

export function CloseResult(arg1:string):Promise<void>;

export function Context():Promise<context.Context>;

export function CountResultRows(arg1:string):Promise<number>;

export function CountTableRows(arg1:string,arg2:dbx.ObjectRef,arg3:string):Promise<number>;

export function CreateDatabase(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateDatabaseFileDialog():Promise<string>;

export function CreateSchema(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateTable(arg1:string,arg2:dbx.TableDefinition):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteDraft(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteSavedQuery(arg1:string):Promise<void>;

export function DropDatabase(arg1:string,arg2:string):Promise<void>;

export function DropObject(arg1:string,arg2:dbx.ObjectRef):Promise<void>;

export function DropSchema(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function DuplicateConnection(arg1:string):Promise<dbx.ConnectionConfig>;

export function ExecuteSQL(arg1:string,arg2:string,arg3:string,arg4:app.ExecuteOptions):Promise<app.ExecuteResponse>;

export function ExplainSQL(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<app.StatementResult>;

export function ExportResultSet(arg1:string,arg2:app.ExportOptions):Promise<app.ExportResult>;

export function FetchRows(arg1:string,arg2:number,arg3:number):Promise<rs.Page>;

export function FormatSQL(arg1:string,arg2:string):Promise<string>;

export function GenerateInsertSQL(arg1:string,arg2:dbx.ObjectRef):Promise<string>;

export function GenerateRowSQL(arg1:string,arg2:app.RowSQLOptions):Promise<string>;

export function GenerateSelectSQL(arg1:string,arg2:dbx.ObjectRef,arg3:number):Promise<string>;

export function GenerateUpdateSQL(arg1:string,arg2:dbx.ObjectRef):Promise<string>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetCellValue(arg1:string,arg2:number,arg3:string):Promise<string>;

export function GetHistory(arg1:number):Promise<Array<store.HistoryEntry>>;

export function GetObjectDDL(arg1:string,arg2:dbx.ObjectRef):Promise<string>;

export function GetResourceStats():Promise<app.ResourceStats>;

export function GetResultStats(arg1:string):Promise<rs.Stats>;

export function GetSavedQueries():Promise<Array<store.SavedQuery>>;

export function GetServerInfo(arg1:string):Promise<dbx.ServerInfo>;

export function GetSettings():Promise<store.Settings>;

export function GetStatementAt(arg1:string,arg2:number,arg3:string):Promise<sqlutil.Statement>;

export function GetTableDefinition(arg1:string,arg2:dbx.ObjectRef):Promise<dbx.TableDefinition>;

export function GetTableStats(arg1:string,arg2:string):Promise<Record<string, app.ObjectNode>>;

export function ImportPlugin(arg1:string):Promise<app.PluginInfo>;

export function ImportPluginDialog():Promise<app.PluginInfo>;

export function InitialAppearance():Promise<string>;

export function LanguagePreference():Promise<string>;

export function ListAllDatabases(arg1:string):Promise<Array<dbx.DatabaseInfo>>;

export function ListConnections():Promise<Array<app.ConnectionState>>;

export function ListDatabases(arg1:string):Promise<Array<dbx.DatabaseInfo>>;

export function ListDrafts():Promise<Array<store.Draft>>;

export function ListEngines():Promise<Array<app.EngineOption>>;

export function ListFavorites():Promise<Array<store.Favorite>>;

export function ListFilterOps():Promise<Array<app.FilterOpInfo>>;

export function ListGroups():Promise<Array<store.Group>>;

export function ListObjects(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<Array<app.ObjectNode>>;

export function ListPlugins():Promise<Array<app.PluginInfo>>;

export function ListSchemas(arg1:string,arg2:string):Promise<Array<dbx.SchemaInfo>>;

export function McpCallTool(arg1:string,arg2:string,arg3:Record<string, any>):Promise<app.McpCallResult>;

export function McpReadResource(arg1:string,arg2:string):Promise<string>;

export function McpResources(arg1:string):Promise<Array<mcp.Resource>>;

export function McpTools(arg1:string):Promise<Array<mcp.Tool>>;

export function MoveConnection(arg1:string,arg2:string):Promise<void>;

export function OpenConnection(arg1:string):Promise<app.ConnectionState>;

export function OpenDatabaseFileDialog():Promise<string>;

export function OpenSQLFileDialog():Promise<string>;

export function OpenTableData(arg1:string,arg2:dbx.ObjectRef,arg3:app.OpenTableOptions):Promise<app.TableDataResult>;

export function PingConnection(arg1:string):Promise<void>;

export function PluginNodeActions(arg1:string,arg2:plugindrv.Node):Promise<Array<plugindrv.Action>>;

export function PreviewAlterTable(arg1:string,arg2:dbx.TableDefinition,arg3:dbx.TableDefinition):Promise<app.DDLPreview>;

export function PreviewChanges(arg1:app.ChangeSet):Promise<app.ChangePreview>;

export function PreviewCreateTable(arg1:string,arg2:dbx.TableDefinition):Promise<app.DDLPreview>;

export function ReadLogTail(arg1:number):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RedisCommand(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RedisDeleteKeys(arg1:string,arg2:string,arg3:Array<string>):Promise<number>;

export function RedisExpireKey(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function RedisGetKey(arg1:string,arg2:string,arg3:string):Promise<dbx.KeyValue>;

export function RedisRenameKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RedisScanKeys(arg1:string,arg2:string,arg3:string,arg4:number):Promise<app.RedisScanResult>;

export function RedisSetKey(arg1:string,arg2:string,arg3:dbx.KeyValue):Promise<void>;

export function RefreshRow(arg1:string,arg2:number):Promise<dbx.Row>;

export function ReleaseMemory():Promise<app.ResourceStats>;

export function RemovePlugin(arg1:string):Promise<void>;

export function RenameGroup(arg1:string,arg2:string):Promise<void>;

export function RenameObject(arg1:string,arg2:dbx.ObjectRef,arg3:string):Promise<void>;

export function ReorderConnections(arg1:Array<string>):Promise<void>;

export function ReorderGroups(arg1:Array<string>):Promise<void>;

export function ResolvedLanguage():Promise<string>;

export function RevealLogFile():Promise<void>;

export function RevealPlugin(arg1:string):Promise<void>;

export function RunPluginAction(arg1:string,arg2:string,arg3:plugindrv.Node,arg4:Record<string, string>):Promise<plugindrv.ActionResult>;

export function SaveConnection(arg1:dbx.ConnectionConfig):Promise<dbx.ConnectionConfig>;

export function SaveDraft(arg1:store.Draft):Promise<void>;

export function SaveFileDialogFor(arg1:string,arg2:string):Promise<string>;

export function SaveGroup(arg1:string):Promise<Array<store.Group>>;

export function SaveQuery(arg1:store.SavedQuery):Promise<store.SavedQuery>;

export function SaveSQLFileDialog(arg1:string):Promise<string>;

export function SaveSettings(arg1:store.Settings):Promise<store.Settings>;

export function Search(arg1:app.SearchRequest):Promise<app.SearchResult>;

export function ServerVariables(arg1:string):Promise<Record<string, string>>;

export function SetCurrentDatabase(arg1:string,arg2:string):Promise<void>;

export function SplitStatements(arg1:string,arg2:string):Promise<Array<sqlutil.Statement>>;

export function StopFetch(arg1:string):Promise<void>;

export function TestConnection(arg1:dbx.ConnectionConfig):Promise<dbx.ServerInfo>;

export function ThemePreference():Promise<string>;

export function TitleBarDoubleClickAction():Promise<string>;

export function ToggleFavorite(arg1:store.Favorite):Promise<boolean>;

export function TruncateTable(arg1:string,arg2:dbx.ObjectRef):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
